# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDoctorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the assignment was established.",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="The doctor assigned to care for the patient.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_mappings",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient being assigned to a doctor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_mappings",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient-Doctor Mapping",
                "verbose_name_plural": "Patient-Doctor Mappings",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "doctor"],
                        name="mappings_pa_patient_334947_idx",
                    ),
                    models.Index(
                        fields=["assigned_at"], name="mappings_pa_assigne_31beec_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "doctor"), name="unique_patient_doctor"
                    )
                ],
            },
        ),
    ]
