# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full legal name of the patient.", max_length=255
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Age of the patient in years (0-120)."
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        help_text="Gender identity of the patient.",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary contact telephone number.", max_length=20
                    ),
                ),
                ("address", models.TextField(help_text="Residential address.")),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Past medical conditions, allergies, or clinical notes.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the patient record was registered.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the patient record was last updated.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Authenticated user who registered and owns this patient record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by"], name="patients_pa_created_15c993_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="patients_pa_created_542792_idx"
                    ),
                ],
            },
        ),
    ]
