# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full professional name of the doctor.",
                        max_length=255,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Medical discipline or clinical specialization (e.g., Cardiology, Neurology).",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number.", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Professional email address.", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the doctor record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the doctor record was last updated.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who registered this doctor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["specialization"], name="doctors_doc_special_037046_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="doctors_doc_created_61e2f4_idx"
                    ),
                ],
            },
        ),
    ]
